version: '3.7'

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server